version: 2
 jobs:
   build:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: 
      - com.qatest.Test1_user_blog_search_user_Samantha
      - com.qatest.Test2_user_blog_search_posts_by_user_Samantha
      - com.qatest.Test3a_user_blog_search_comments_by_user_Samantha
      - com.qatest.Test3b_user_blog_to_validate_email_formats_in_comments
